### ISSUE TITLE
Only OSX has setAsDockMenu

### ISSUE THREAD

**Issue by squeakbat** [djcapelis/chimery#10]

**Comment by squeakbat** [comment]
Is __APPLE_CC__ the proper ifdef?

**Comment by djcapelis** [comment]
Probably best to use Qt's Q_WS_MAC define, which should do the right thing,
I think.  (For instance if you wanted to build a version to use X11 on OS X
the right thing would still happen.)

**Comment by squeakbat** [comment]
Can I check it in?

diff --git a/chimerymenus.cpp b/chimerymenus.cpp
index e77f777..f855ccc 100644
--- a/chimerymenus.cpp
+++ b/chimerymenus.cpp
@@ -11,7 +11,9 @@ ChimeryMenus::ChimeryMenus(ChimeryMainWindow * mwin, ChimeryAboutWindow * awin)
     about = new QAction("&About Chimery", this);
     sched->setEnabled(false);
     sched->setShortcuts(QKeySequence::Undo);
+#ifdef Q_WS_MAC
     menu->setAsDockMenu();
+#endif
     menu->addAction(sched);
     menu->addSeparator();
     menu->addAction(about);

**Comment by djcapelis** [comment]
Apparently Qt5 eliminated the Q_WS* macros.  Q_OS_OSX seems to be thing to
do now.

**Comment by djcapelis** [comment]
s/WS/OS/  (doesn't matter if it's _OSX or _MAC, though the latter is
more compatible across Qt versions so maybe that's actually the better
one.) and I'd love to apply it to the tree!  Want to pull request it or
should I just apply it as a patch?

**Comment by squeakbat** [comment]
I can't really test it.  Or, I can test anything that isn't defined, but I can't see if OSX defines it.

And this stupid thing didn't indent the diffs right, but you get the idea, and it's only two lines.

**Comment by djcapelis** [comment]
Yes, sounds great, I'll commit a fix after I sleep.  Meant to do this days
ago but this got sent to my stars folder and joined a large heap.

>

**Comment by squeakbat** [comment]
Also, I don't really know how to use git.  Every attempt at creating a sensible mental model has so far failed.

Yes, sleep.  I should do that too.  I'm supposed to go into work tomorrow.  Imagine that.

**Comment by djcapelis** [comment]
Oh?  You'll have to tell me more when we're not just talking via github's
issue tracker.  Sorry I promised myself to be better about sleep otherwise
I totally would have walked over to my computer and committed this already.

>
